name: Publish

on:
  workflow_dispatch:
    inputs:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev libsecp256k1
      - run: cargo fmt --check
      - run: cargo build --verbose
      - run: cargo test --lib -- --test-threads=1
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_REGISTRY_TOKEN }}
          args: --no-verify
